version: '3.1'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - fastapi

